### ISSUE TITLE
MycetOS Meetings 2022

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/General-Start-Here#10]
Hi @OpenSourceMycetoma/corecontrib - do we already have a meeting schedule for 2022?

We have a nice system for templates (https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/59) and nice recent examples of write-ups (https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/66).

**Comment by mattodd** [comment]
Anyone want to express a preference here? I'm happy with Fourth Tuesday of each month at e.g. 1pm, but that may not be great for other T-zones?
@wwjvdsande @Wilson-Lm @MFernflower @dmitrij176 @fantasy121 @MA-Jjingyi @kym834 @alintheopen ?
Also keen to ensure these are in the diary for all and any others e.g. @AndyBishopSevenoaks @bendndi etc

**Comment by wwjvdsande** [comment]
@matttodd, I had the meeting in my agenda for upcomming tuesday at 13:00 Amsterdam time. I think that is 12:00 UK time. I think that was the time slot we had during wintertime. At summertime it would switch again. However if this is not good foor the other time zones I m open to changes of course.

**Comment by matttodd** [comment]
Hello,

I believe you have the wrong person.

All the best,
Matt Todd

**Comment by dmitrij176** [comment]
I am ok with the old schedule unless it intereferes/coincides with other people schedules. Can USYD team (@fantasy121 , @kym834) express their opinion on the matter?

**Comment by kym834** [comment]
@mattodd, @wwjvdsande @dmitrij176 @fantasy121  Happy with fourth Tuesday as before but I've a preference to move to a slightly earlier time slot. 
8PM Sydney --- 9AM London --- 10AM Amsterdam
https://www.timeanddate.com/worldclock/converter.html?iso=20220122T090000&p1=136&p2=16&p3=240

**Comment by MFernflower** [comment]
9am London is 4 am in east coast us

**Comment by wwjvdsande** [comment]
@mattodd @dmitrij176 @MA-Jjingyi @MFernflower @fantasy121 @Wilson-Lm  for me either time slots are OK. I have to move one meeting if we change but that will not be a problem. However, as far as I know the next meeting is scheduled for tomorrow. May be for tomorrow we leave the time as it was (I'm not sure if everyone will catch this in time before tomorrow and if others need to move meetings as well if we are going to meet at a different time that might be too late). We can tomorrow than also make the final decision on the meeting time in the future.

**Comment by mattodd** [comment]
OK, so tomorrow's meeting (25th Jan) should be at noon UK time, 1pm EU time, 7am EST, 11pm Sydney? Then we can discuss. Is the link the same? i.e. https://uni-sydney.zoom.us/j/99281549497 or has that expired?

**Comment by mattodd** [comment]
Might be an idea to do a nice Zoom gallery screenshot so we can post something online about our work for World NTD Day on Jan 30th.
https://www.who.int/news-room/events/detail/2022/01/26/default-calendar/wntdd-Achieving-health-equity-to-end-the-neglect-of-poverty-related-diseases

**Comment by wwjvdsande** [comment]
Is an excellent idea!

**Comment by MFernflower** [comment]
I can do 1pm uk time 4th of each month

@mattodd

**Comment by mattodd** [comment]
Closing since taken on in https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/67
